---
- name: Get the username running the deploy
  become: false
  local_action: command whoami
  register: username_on_the_host

- name: Create project directory
  become: yes
  file:
    path: "{{ deployment_path }}"
    state: directory
    mode: '0777'

- name: Transfer docker-compose project to remote
  synchronize:
    src: "{{ local_deployment_path }}"
    dest: "{{ deployment_path }}"
    recursive: True
    delete: True
    rsync_opts:
      - "--exclude=docker/data"

- name: "Stop all services"
  become: yes
  shell: "docker-compose -f {{ deployment_path }}/docker/docker-compose.yml down"
  args:
    chdir: "{{ deployment_path }}/docker"

- name: "Rebuild project {% if dct_recreate == True %}Docker Compose Recreate is enabled - build is slower{% endif %}"
  become: yes
  shell: "docker-compose -f {{ deployment_path }}/docker/docker-compose.yml build {% if dct_recreate == True %}--force-recreate{% endif %}"
  args:
    chdir: "{{ deployment_path }}/docker"

- name: "Start all services"
  become: yes
  shell: "docker-compose -f {{ deployment_path }}/docker/docker-compose.yml up -d"
  args:
    chdir: "{{ deployment_path }}/docker"
  environment:
    HOSTNAME: "{{ public_hostname }}"