---
- hosts: head_servers
  vars:
    local_deployment_path: "{{ playbook_dir }}/.."
    deployment_path: /deployments/tt/compose
    dct_recreate: False
  roles:
#    - common
    - rsync
    - docker-compose
    - main-app